import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :app, AppWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# HTTPS is terminated UPSTREAM by Cloudflare — the tunnel forwards plain HTTP to the container,
# and the intermediate hops don't reliably pass `x-forwarded-proto: https`. With Phoenix-level
# `force_ssl` on, Plug.SSL sees scheme: http and redirect-loops to https. So we let Cloudflare
# enforce HTTPS at the edge instead (the container is only reachable THROUGH the tunnel, so there's
# no plain-HTTP exposure to guard). URL/link generation is still https via `url:` in runtime.exs.
#
# If you ever run WITHOUT a TLS-terminating proxy, re-enable this and make sure whatever proxy is
# in front passes `x-forwarded-proto: https`:
#
#   config :app, AppWeb.Endpoint,
#     force_ssl: [rewrite_on: [:x_forwarded_proto], exclude: [hosts: ["localhost", "127.0.0.1"]]]

# Pre-open outbound connection pools at boot so the first user turn doesn't eat the host's cold
# connect (~9s post-idle). Also logs per-host connect times. See App.Http.Warmer.
config :app, start_pool_warmer: true

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
